name: Generate Android

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: rm -rf android
      - run: flutter create . --platforms=android
      - run: cp app/google-services.json android/app/google-services.json
      - run: git add android && git commit -m "Generate Android" || true
      - run: git push
