name: hr_ride
description: HR Ride App

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_places_flutter: ^2.1.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
